### ISSUE TITLE
interest in donating this project to actix-extras

### ISSUE THREAD

**Issue by robjtede** [jjpe/actix-settings#1]
An Actix Web user recently posted about updating to v4 but was a bit stuck due to their reliance on this crate for set up. What do you think about donating the project to the @actix org so we can keep it up to date and add the other desirable features like TLS options?

If so, all we'd need is for you to submit a PR to the actix-extras repo and to assign me as an owner on crates.io.

**Comment by jjpe** [comment]
Hi, sorry for the late reply.

> What do you think about donating the project to the https://github.com/actix org so we can keep it up to date and add the other desirable features like TLS options?

Actually that sounds great :)

> submit a PR to the actix-extras repo

Sure, but containing what, exactly? 
If it's about the code, it seems like your fork is at present better positioned for that.

> assign me as an owner on crates.io

I've sent you an invite.

**Comment by robjtede** [comment]
Excellent news. Thank you.

> Sure, but containing what, exactly?
> If it's about the code, it seems like your fork is at present better positioned for that.

Yeah since we've already started on the update it would be easier to manage that from my end now.

Just one more necessary admin thing first. Are you okay with the crate being re-licenced using the dual MIT / Apache v2.0 license we use for all our crates?

**Comment by jjpe** [comment]
> Just one more necessary admin thing first. Are you okay with the crate being re-licenced using the dual MIT / Apache v2.0 license we use for all our crates?

I have no objections to relicensing the project in that manner.

Some other miscellaneous stuff:
* This might be a good moment to run the project through `cargo fmt` and `cargo clippy`. This crate was written before I started using those tools regularly, and in retrospect it shows.
* I assume and hope the plan is to (mostly) keep the API the same? I still use the crate myself (with an outdated actix version, which this might help fix) and having to rewrite the parts that consume the APIs of this crate would be undesirable if it can be avoided.

**Comment by robjtede** [comment]
> This might be a good moment to run the project through cargo fmt and cargo clippy.

For sure.

> I assume and hope the plan is to (mostly) keep the API the same? 

Yes, the idea is to just update the dependencies for now. If you're still interested in providing review feedback, I'll add you to the contibutors group and tag you on PRs.

**Comment by robjtede** [comment]
Here's the adoption PR: https://github.com/actix/actix-extras/pull/270

**Comment by jjpe** [comment]
> If you're still interested in providing review feedback, I'll add you to the contibutors group and tag you on PRs.

Sounds good to me.
